### ISSUE TITLE
Disables On Startup

### ISSUE THREAD

**Issue by 2veryicey** [Rammelkast/AntiCheatReloaded#10]
When Reloading Or Rebooting The Plugin Disables On Startup. Error:
```
10.09 15:47:56 [Server] INFO Disabling AntiCheatReloaded v1.4.0-ALPHA
10.09 15:47:56 [Server] INFO ... 24 more
10.09 15:47:56 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
10.09 15:47:56 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
10.09 15:47:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_77]
10.09 15:47:56 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
10.09 15:47:56 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:637) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:738) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
10.09 15:47:56 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:43) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:556) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:783) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:375) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.2.jar:git-Paper-852]
10.09 15:47:56 [Server] INFO at net.gravitydevelopment.anticheat.AntiCheat.onEnable(AntiCheat.java:95) ~[?:?]
10.09 15:47:56 [Server] INFO java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
10.09 15:47:56 [Server] ERROR Error occurred while enabling AntiCheatReloaded v1.4.0-ALPHA (Is it up to date?)
10.09 15:47:56 [Server] INFO Running version v1_10_R1...
10.09 15:47:56 [Server] INFO Enabling AntiCheatReloaded v1.4.0-ALPHA
```

**Comment by helptiger** [comment]
ProtocolLib not loaded! https://www.spigotmc.org/resources/protocollib.1997/

**Comment by 2veryicey** [comment]
oh...I am an idiot...I looked for dependancies on the plugin page...not in the text itself

**Comment by Rammelkast** [comment]
Thanks @helptiger for helping ;)
- Issue closed -
