### ISSUE TITLE
humm this happend

### ISSUE THREAD

**Issue by Bob123360** [Rammelkast/AntiCheatReloaded#134]
[18:44:00 INFO]: Starting Minecraft server on *:25565
[18:44:00 INFO]: Using default channel type
[18:44:00 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[18:44:03 WARN]: Legacy plugin JustTPA v1.0.0 does not specify an api-version.

**[18:44:03 ERROR]: Could not load 'plugins\AntiCheatReloaded.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency ProtocolLib. Please download and install ProtocolLib to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.5.jar:git-Paper-466]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-466]
        at java.lang.Thread.run(Thread.java:832) [?:?]**

**Comment by Emile-Gostlow** [comment]
You need to also install ProtocolLib, you can find it here [https://www.spigotmc.org/resources/protocollib.1997/](https://www.spigotmc.org/resources/protocollib.1997/)

**Comment by Rammelkast** [comment]
As noted by @Emile-Gostlow, you need protocollib.
