### ISSUE TITLE
Error in test critical

### ISSUE THREAD

**Issue by MarvanCZ** [Rammelkast/AntiCheatReloaded#15]
[19:47:11 INFO]: [AntiCheat] JaLegenda has just entered the High hack group.
[19:47:11 INFO]: [AntiCheat] JaLegenda's last failed check was: Criticals.
[19:47:11 INFO]: [AntiCheat] Type '/anticheat report JaLegenda' for more information.
[19:47:11 INFO]: [AntiCheat] JaLegenda failed Criticals, tried to do a critical without needed conditions
[19:47:11 INFO]: JaLegenda lost connection: žcKicked by AntiCheatReloaded
[19:47:11 INFO]: JaLegenda left the game
[19:47:11 INFO]: [AntiCheat] JaLegenda was kicked for hacking. (Criticals)
[19:47:11 WARN]: handleDisconnection() called twice
[19:47:11 WARN]: [AntiCheatReloaded] Task #25362 for AntiCheatReloaded v1.4.0-ALPHA generated an exception
java.lang.NullPointerException
        at net.gravitydevelopment.anticheat.util.NPC_1_10$3.run(NPC_1_10.java:162) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-latest.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-latest.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-latest.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-latest.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-latest.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-latest.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
>

**Comment by Rammelkast** [comment]
What ACR and spigot/bukkit version are you running?

**Comment by MarvanCZ** [comment]
Version v1.10.R1
