### ISSUE TITLE
IllegalArgumentException on plugin load

### ISSUE THREAD

**Issue by gxtu** [Rammelkast/AntiCheatReloaded#155]
[This recent change to the number of threads](https://github.com/Rammelkast/AntiCheatReloaded/commit/ed127276f050dc157874cfbb82e7d5a31b061b5e#diff-db8e8fe99858943e933ccf0fb8064f19f1378c81e1d852ccbcf229eeeee3a991R74) causes an exception for me when the plugin is loaded. When I change the line back to what it was before that commit, everything is working fine. The server is running Paper 1.17 (git-Paper-69) on a VPS with 2 CPU cores.

Looking at the second exception, maybe it would be a good idea to check if `config` is `null`, before accessing it in `onDisable`, in case an error occurs before it has been initialized like in this case.

Thanks for the great work! It is much appreciated.

---

```
[XX:XX:XX ERROR]: Error occurred while enabling AntiCheatReloaded v1.9.9-PRE (Is it up to date?)
java.lang.IllegalArgumentException: null
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1295) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1181) ~[?:?]
        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:92) ~[?:?]
        at com.rammelkast.anticheatreloaded.AntiCheatReloaded.onEnable(AntiCheatReloaded.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-69]
        at java.lang.Thread.run(Thread.java:831) [?:?]

[XX:XX:XX INFO]: [AntiCheatReloaded] Disabling AntiCheatReloaded v1.9.9-PRE
[XX:XX:XX INFO]: [AntiCheatReloaded] Saving user levels...
[XX:XX:XX ERROR]: Error occurred while disabling AntiCheatReloaded v1.9.9-PRE (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.rammelkast.anticheatreloaded.config.Configuration.getLevels()" because "com.rammelkast.anticheatreloaded.AntiCheatReloaded.config" is null
        at com.rammelkast.anticheatreloaded.AntiCheatReloaded.onDisable(AntiCheatReloaded.java:185) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-69]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Rammelkast** [comment]
Thanks for reporting this. Can you test if it's fixed using the latest CI release?
It can be found here: https://ci.rammelkast.com/job/AntiCheatReloaded/2/com.rammelkast.anticheatreloaded$AntiCheatReloaded/

**Comment by abba23** [comment]
Yes, it's loading just fine now.
