### ISSUE TITLE
NullPointerException when trying to get report for offline player

### ISSUE THREAD

**Issue by gxtu** [Rammelkast/AntiCheatReloaded#156]
It looks like since [this change](https://github.com/Rammelkast/AntiCheatReloaded/commit/7739eb9ca0b005b8eef940cf25cbec69d7ded22e#diff-6244e959079b2d4d929294b4b3f4faf64d58c935a47305b07683b915c493060aR98), `getPlayerPing()` throws an exception on version 1.17 if `player` is `null` instead of just returning `-1`. This happens when you try to get the report for an offline player.

```
[XX:XX:XX ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'acr' in plugin AntiCheatReloaded v1.9.9-PRE
         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-69]
         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-69]
         at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2185) ~[?:?]
         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1996) ~[?:?]
         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1977) ~[?:?]
         at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
         at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-69]
         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-69]
         at java.lang.Thread.run(Thread.java:831) [?:?]
 Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getPing()" because "player" is null
         at com.rammelkast.anticheatreloaded.util.VersionUtil.getPlayerPing(VersionUtil.java:108) ~[?:?]
         at com.rammelkast.anticheatreloaded.util.User.getPing(User.java:409) ~[?:?]
         at com.rammelkast.anticheatreloaded.command.executors.CommandReport.playerReport(CommandReport.java:182) ~[?:?]
         at com.rammelkast.anticheatreloaded.command.executors.CommandReport.execute(CommandReport.java:94) ~[?:?]
         at com.rammelkast.anticheatreloaded.command.CommandBase.run(CommandBase.java:66) ~[?:?]
         at com.rammelkast.anticheatreloaded.command.CommandHandler.onCommand(CommandHandler.java:64) ~[?:?]
         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Paper-69]
         ... 21 more
```

**Comment by ENDER1355** [comment]
the devs are so fast :O
