### ISSUE TITLE
NullPointerException when leaving nether trough portal

### ISSUE THREAD

**Issue by gxtu** [Rammelkast/AntiCheatReloaded#158]
I'm getting sporadic NullPointerExceptions on Minecraft 1.17 (git-Paper-69), which can be reproduced for example by leaving the nether through a portal.

The problem appears to be that since Java 15, all the JavaScript script engines have been removed, causing [`getEngineByName("js")`](https://github.com/Rammelkast/AntiCheatReloaded/blob/master/src/main/java/com/rammelkast/anticheatreloaded/util/rule/ConditionalRule.java#L52) to return `null`.

Minecraft 1.17 servers now require Java 16 to run though.

---

```
[XX:XX:XX WARN]: [AntiCheatReloaded] Task #16457 for AntiCheatReloaded v1.9.9-PRE generated an exception
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "com.rammelkast.anticheatreloaded.util.rule.ConditionalRule.engine" is null
        at com.rammelkast.anticheatreloaded.util.rule.ConditionalRule.check(ConditionalRule.java:70) ~[?:?]
        at com.rammelkast.anticheatreloaded.util.User.increaseLevel(User.java:162) ~[?:?]
        at com.rammelkast.anticheatreloaded.event.EventListener.log(EventListener.java:90) ~[?:?]
        at com.rammelkast.anticheatreloaded.check.packet.BadPacketsCheck$1.run(BadPacketsCheck.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-69]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Rammelkast** [comment]
Temporarily handled as of a1f7a0c, awaiting rules engine recode.
