### ISSUE TITLE
Error when hit entity 

### ISSUE THREAD

**Issue by MarvanCZ** [Rammelkast/AntiCheatReloaded#17]
[03:09:37] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_11_R1.EntityPlayer.<init>(net.minecraft.server.v1_11_R1.World)
[03:09:37] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Unknown Source)
[03:09:37] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Unknown Source)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.EntityTypes.a(SourceFile:153)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.Entity.teleportTo(Entity.java:2238)
[03:09:37] [Server thread/WARN]: 	at net.gravitydevelopment.anticheat.util.NPC_1_11.move(NPC_1_11.java:132)
[03:09:37] [Server thread/WARN]: 	at net.gravitydevelopment.anticheat.check.combat.KillAuraCheck.doMove(KillAuraCheck.java:87)
[03:09:37] [Server thread/WARN]: 	at net.gravitydevelopment.anticheat.event.PlayerListener.onPlayerMove(PlayerListener.java:324)
[03:09:37] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[03:09:37] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:09:37] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[03:09:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[03:09:37] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[03:09:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[03:09:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:609)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[03:09:37] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[03:09:37] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[03:09:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[03:09:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Rammelkast** [comment]
What ACR and Spigot/Bukkit are you using?

**Comment by MarvanCZ** [comment]
AntiCheatReloaded 1.5.2-ALPHA (the 1.11 update)
Spigot Version v1_11_R1

**Comment by Rammelkast** [comment]
Can you send a pastebin with the entire log?

**Comment by MarvanCZ** [comment]
This is a Debug.
ARC = http://pastebin.com/3ek9QV7f
Log server= http://sharegadget.com/485415152

**Comment by MarvanCZ** [comment]
Fix Please. There anything you want to send?
