### ISSUE TITLE
Pre Relese

### ISSUE THREAD

**Issue by KnockBackGod** [Rammelkast/AntiCheatReloaded#175]
Could Not Enable Anti Cheat (1.17.1)

[14:50:12 INFO]: [AntiCheatReloaded] Enabling AntiCheatReloaded v1.9.9-PRE
[14:50:13 ERROR]: Error occurred while enabling AntiCheatReloaded v1.9.9-PRE (Is it up to date?)
java.lang.IllegalArgumentException: null
at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1295) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1181) ~[?:?]
at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:92) ~[?:?]
at com.rammelkast.anticheatreloaded.AntiCheatReloaded.onEnable(AntiCheatReloaded.java:75) ~[AntiCheatReloaded (1).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:970) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.Bukkit.reload(Bukkit.java:769) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-261]
at java.lang.Thread.run(Thread.java:831) [?:?]
[14:50:13 INFO]: [AntiCheatReloaded] Disabling AntiCheatReloaded v1.9.9-PRE
[14:50:13 ERROR]: Error occurred while disabling AntiCheatReloaded v1.9.9-PRE (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.rammelkast.anticheatreloaded.config.Configuration.getLevels()" because "com.rammelkast.anticheatreloaded.AntiCheatReloaded.config" is null
at com.rammelkast.anticheatreloaded.AntiCheatReloaded.onDisable(AntiCheatReloaded.java:185) ~[AntiCheatReloaded (1).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:970) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.Bukkit.reload(Bukkit.java:769) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-261]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-261]
at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Rammelkast** [comment]
You need ProtocolLib as well. Also try the latest pre-release build from here: https://ci.rammelkast.com/job/AntiCheatReloaded/lastSuccessfulBuild/com.rammelkast.anticheatreloaded$AntiCheatReloaded/
