### ISSUE TITLE
Stacking scaffolding throws error

### ISSUE THREAD

**Issue by HCl-not-HCi** [Rammelkast/AntiCheatReloaded#193]
When stacking scaffolding by right clicking the scaffolding which I have placed on the floor (= building a tower of scaffolding), an error is thrown in the console:

```
[21:26:43] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to AntiCheatReloaded v1.10.1-PRE
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:317) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:538) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1527) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.block.BlockFace.getModX()" because "face" is null
        at com.rammelkast.anticheatreloaded.check.player.IllegalInteract.checkBlockPlace(IllegalInteract.java:89) ~[?:?]
        at com.rammelkast.anticheatreloaded.check.player.IllegalInteract.performCheck(IllegalInteract.java:48) ~[?:?]
        at com.rammelkast.anticheatreloaded.event.BlockListener.onBlockPlace(BlockListener.java:47) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor221.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3271-Spigot-3892929-cef1fda]
        ... 21 more
```

AntiCheatReloaded version: Based on 84ddce8f1e3eb78b6d35ab8ec49e041dd2347f21
Server: Spigot 1.17.1
ProtocolLib: 4.7.0

**Comment by HCl-not-HCi** [comment]
Thank you!
