### ISSUE TITLE
walking up slabs flags as verticalspeed (step)

### ISSUE THREAD

**Issue by LogVezzz** [Rammelkast/AntiCheatReloaded#205]
when walking up stairs using slabs it glitches and flags as vertical speed also know as step, i tryied tuning it with no succes, disablying it is my solution as for now

**Comment by Rammelkast** [comment]
What are your ACR and server versions?

**Comment by LogVezzz** [comment]
> What are your ACR and server versions?

server: spigot 1.12.2
ACR: 1.10.2

**Comment by Wolfgang683** [comment]
I have this issue as well, it doesn't happen every time. I have a bridge that uses slabs and normally doesn't trigger this, but i have a spiral going around a single block and it triggers it every time. I also get a lot of console spam, i'm not sure if its related to this or could be another check causing the console spam. Haven't looked specifically

paper 1.12.2
ACR: 1.10.2

**Comment by Rammelkast** [comment]
> I have this issue as well, it doesn't happen every time. I have a bridge that uses slabs and normally doesn't trigger this, but i have a spiral going around a single block and it triggers it every time. I also get a lot of console spam with errors, i'm not sure if its related to this or could be another check causing the console spam. Haven't looked specifically
> 
> paper 1.12.2 ACR: 1.10.2

Can you send a log file of the console spam?

**Comment by Wolfgang683** [comment]
[11:19:22] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AntiCheatReloaded v1.10.2
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Player.isRiptiding()'
	at com.rammelkast.anticheatreloaded.check.combat.KillAuraCheck.checkAngle(KillAuraCheck.java:102) ~[?:?]
	at com.rammelkast.anticheatreloaded.event.EntityListener.onEntityDamage(EntityListener.java:117) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:620) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:523) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:652) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1415) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:888) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityHorseAbstract.damageEntity(EntityHorseAbstract.java:166) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1028) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1397) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1724) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:833) [?:?]
