### ISSUE TITLE
Bug error.

### ISSUE THREAD

**Issue by puzusu** [Rammelkast/AntiCheatReloaded#34]
[12:28:58 ERROR]: Error occurred while enabling AntiCheatReloaded v1.5.5-ALPHA (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
        at net.gravitydevelopment.anticheat.AntiCheat.onEnable(AntiCheat.java:96) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.2.jar:git-Bukkit-1a71021]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
        ... 12 more

**Comment by Rammelkast** [comment]
Please install ProtocolLib.
