### ISSUE TITLE
NPE with blink check

### ISSUE THREAD

**Issue by Rammelkast** [Rammelkast/AntiCheatReloaded#37]
User-reported error;
`[AntiCheatReloaded] Unhandled exception occured in onPacketRec eiving(PacketEvent) for AntiCheatReloaded
java.lang.NullPointerException
at com.rammelkast.anticheatreloaded.check.movement.BlinkCheck$2.onPacket Receiving(BlinkCheck.java:47) ~[AntiCheatReloaded.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceiv ingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.1-SNAPSHOT-b 348]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacket Recieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.1-SNAPSHOT-b348 ]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(Pack etFilterManager.java:610) [ProtocolLib.jar:4.2.1-SNAPSHOT-b348]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecie ving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.1-SNAPSHOT-b348]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived (ProtocolInjector.java:323) [ProtocolLib.jar:4.2.1-SNAPSHOT-b348]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiv ing(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.1-SNAPSHOT-b348]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelI njector.java:541) [ProtocolLib.jar:4.2.1-SNAPSHOT-b348]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD ecoder.java:249) [PaperSpigot.jar:git-Paper-1071]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage Decoder.java:149) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst ractChannelHandlerContext.java:333) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra ctChannelHandlerContext.java:319) [PaperSpigot.jar:git-Paper-1071]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage Decoder.java:163) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst ractChannelHandlerContext.java:333) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra ctChannelHandlerContext.java:319) [PaperSpigot.jar:git-Paper-1071]
at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(C hannelInjector.java:273) [ProtocolLib.jar:4.2.1-SNAPSHOT-b348]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst ractChannelHandlerContext.java:333) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra ctChannelHandlerContext.java:319) [PaperSpigot.jar:git-Paper-1071]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage Decoder.java:163) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst ractChannelHandlerContext.java:333) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra ctChannelHandlerContext.java:319) [PaperSpigot.jar:git-Paper-1071]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHa ndler.java:150) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst ractChannelHandlerContext.java:333) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra ctChannelHandlerContext.java:319) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne lPipeline.java:787) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra ctNioByteChannel.java:130) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav a:511) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve ntLoop.java:468) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja va:382) [PaperSpigot.jar:git-Paper-1071]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [PaperSp igot.jar:git-Paper-1071]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread EventExecutor.java:116) [PaperSpigot.jar:git-Paper-1071]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[01:28:04 ERROR]: Parameters:
net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook@9299 d7a[
x=225.14945195849225
y=63.629224155552365
z=-213.30000001192093
yaw=-269.10077
pitch=12.600097
f=false
hasPos=true
hasLook=true
]`

**Comment by Rammelkast** [comment]
Issue caused by invalid config. Closing.
