### ISSUE TITLE
Could not pass event BlockBreakEvent to AntiCheatReloaded v1.3.0-ALPHA-b27

### ISSUE THREAD

**Issue by Razzer123** [Rammelkast/AntiCheatReloaded#4]
[11:20:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AntiCheatReloaded v1.3.0-ALPHA-b27
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Bukkit-efe04b8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-efe04b8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-Bukkit-efe04b8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:285) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:214) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:622) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Bukkit-efe04b8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [server.jar:git-Bukkit-efe04b8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Bukkit-efe04b8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException

**Comment by Rammelkast** [comment]
Temporarily fixed in latest commit.
