### ISSUE TITLE
A bunch of error messages in my logs

### ISSUE THREAD

**Issue by SteelCat666** [Rammelkast/AntiCheatReloaded#40]
Hi,

Im running a small server using your plugin, not really sure if this is normal but every time a player moves it generates an error message like the one below, my logs explode to 3 gigs in an hour when there are a lot of players, can you please inform me of any updates, your anticheat is the best i've found so far. but can you please review this error and fix it

Thanks guys :)

```

[08:52:51 ERROR]: Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.6.0-ALPHA
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:602) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
        at net.gravitydevelopment.anticheat.event.PlayerListener.onPlayerMove(PlayerListener.java:325) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
        at net.gravitydevelopment.anticheat.event.PlayerListener.onPlayerMove(PlayerListener.java:325) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.11.2.jar:git-Bukkit-d219213]
        ... 15 more

```

**Comment by SteelCat666** [comment]
These errors are not a major problem but i have my own automatised care system for my servers, i'm using zabbix to track logs, i've filtered the errors out with regex but it still takes a lot of time for my zabbix to read and process all the logs when there are so many errors in it

**Comment by Rammelkast** [comment]
Please download the ProtocolLib plugin.
