### ISSUE TITLE
User-reported NPE

### ISSUE THREAD

**Issue by Rammelkast** [Rammelkast/AntiCheatReloaded#46]
[22:12:56 INFO]: Zafiro93 issued server command: /anticheat report JosiMax
[22:12:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'anticheat' in plugin AntiCheatReloaded v1.6.2-ALPHA
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
at com.rammelkast.anticheatreloaded.command.executors.CommandReport.execute(CommandReport.java:85) ~[?:?]
at com.rammelkast.anticheatreloaded.command.CommandBase.run(CommandBase.java:65) ~[?:?]
at com.rammelkast.anticheatreloaded.command.CommandHandler.onCommand(CommandHandler.java:63) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[vanilla-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
... 15 more

**Comment by Rammelkast** [comment]
NPE seems to be gone. Closing issue.
