### ISSUE TITLE
Didn't load so heres the error

### ISSUE THREAD

**Issue by ShellUserMyDude** [Rammelkast/AntiCheatReloaded#51]
[22:07:29] [Server thread/ERROR]: Could not load 'plugins\AntiCheatReloaded.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ProtocolLib
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:221) [spigot.jar:git-Spigot-d05d3c1-087a2cf]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot.jar:git-Spigot-d05d3c1-087a2cf]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot.jar:git-Spigot-d05d3c1-087a2cf]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764) [spigot.jar:git-Spigot-d05d3c1-087a2cf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by Rammelkast** [comment]
You need to install ProtocolLib. Please remember that this project is no longer supported and likely will not work with 1.14.
