### ISSUE TITLE
PlayerMoveEvent

### ISSUE THREAD

**Issue by Timmy109** [Rammelkast/AntiCheatReloaded#80]
Hi, this error keeps coming up in console whenever it gives a false positive.
False positives come up heaps with this plugin and I was wondering if there is a possible way to fix it?

But here is the error regardless:
It absolutely spams the sh*t out of console lol
---------------------------------------------------------------------------------------------------------
[ERROR] .... Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.8.1

java.lang.ClassCastException: java.lang.Integer incompatible with java.lang.Double

at com.sun.proxy.$Proxy69.FLIGHT_BLOCK_LIMIT(Unknown Source) ~[?:?]

at com.rammelkast.anticheatreloaded.check.movement.FlightCheck.runCheck(FlightCheck.java:77) ~[?:?]

at com.rammelkast.anticheatreloaded.event.PlayerListener.onPlayerMove(PlayerListener.java:350) ~[?:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor473.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-239]

at org.bukkit.plugin.EventExecutor$$Lambda$2853.00000000C99124D0.execute(Unknown Source) ~[?:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-239]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-239]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1142) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4103.000000008D058C80.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-239]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

[ERROR] .... Could not pass event PlayerMoveEvent to AntiCheatReloaded v1.8.1

java.lang.ClassCastException: java.lang.Integer incompatible with java.lang.Double

at com.sun.proxy.$Proxy69.FLIGHT_BLOCK_LIMIT(Unknown Source) ~[?:?]

at com.rammelkast.anticheatreloaded.check.movement.FlightCheck.runCheck(FlightCheck.java:77) ~[?:?]

at com.rammelkast.anticheatreloaded.event.PlayerListener.onPlayerMove(PlayerListener.java:350) ~[?:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor473.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-239]

at org.bukkit.plugin.EventExecutor$$Lambda$2853.00000000C99124D0.execute(Unknown Source) ~[?:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-239]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-239]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1142) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4103.000000008D058C80.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-239]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-239]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
---------------------------------------------------------------------------------------

**Comment by Rammelkast** [comment]
It says that java.lang.Integer incompatible with java.lang.Double for FLIGHT_BLOCK_LIMIT.
This means that you have configured FLIGHT_BLOCK_LIMIT in magic.yml to be an integer (a rounded number with no decimals) instead of a double (e.g. 5.0 or 4.5). If your FLIGHT_BLOCK_LIMIT is, for example, 5. You should change it to 5.0.
